sudo: required
services:
    - docker

before_install:
    - docker build -t dmaesj/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dmaesj/docker-react npm run test -- --coverage
